global:
  resolve_timeout: 1m
  smtp_from: m.glushkova1@gmail.com
  smtp_smarthost: smtp.gmail.com:587

route:
  receiver: "gmail-notifications"

receivers:
  - name: "gmail-notifications"
    email_configs:
      - to: m.glushkova1@gmail.com
        from: alertmanager@gmail.com
        smarthost: smtp.gmail.com:587
        auth_username: m.glushkova1@gmail.com
        auth_identity: m.glushkova1@gmail.com
        auth_password: fnayxuqwavmboksa
        send_resolved: true
